workflows:
  isignapp-ios:
    name: Build IPA for device
    environment:
      vars:
        # Setează dacă vrei codare automată (opțional)
        # MATCH_PASSWORD: Encrypted(...)
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods || true
          pod install || true
      - name: Build and archive IPA
        script: |
          xcodebuild archive \
            -workspace YourWorkspace.xcworkspace \
            -scheme ISignApp \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ISignApp.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            PROVISIONING_PROFILE_SPECIFIER="YourProvisioningProfileName"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ISignApp.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/*.ipa
    publishing:
      scripts:
        - echo "IPA build complete."
