workflows:
  isignapp-ios:
    name: Build unsigned IPA
    environment: {}
    scripts:
      - name: Build app without signing
        script: |
          xcodebuild clean archive \
            -workspace YourWorkspace.xcworkspace \
            -scheme ISignApp \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ISignApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO
      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ISignApp.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/*.ipa
