workflows:
  isignapp-ios:
    name: Build only .app (unsigned)
    environment:
      vars:
        XCODE_PROJECT: "ISignApp.xcodeproj"
        XCODE_SCHEME: "ISignApp"
        XCODE_CONFIGURATION: "Release"
        BUNDLE_ID: "com.perfectshot.isignapp"
    scripts:
      - name: Build .app (unsigned)
        script: |
          xcodebuild clean build \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -configuration $XCODE_CONFIGURATION \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            BUILD_DIR=$CM_BUILD_DIR/build
    artifacts:
      - build/Release-iphoneos/ISignApp.app
